version: "3.8"
services:
  wordpress:
    build: .
    volumes:
      - wordpress:/var/www/html
      - ./src/themes:/var/www/html/web/app/themes
      - ./src/mu-plugins:/var/www/html/web/app/mu-plugins
      - ./.env:/var/www/html/.env:ro
    depends_on:
      - db

  server:
    image: nginx:alpine
    depends_on:
      - wordpress
      - db
    ports:
      - ${WP_PORT}:80
    volumes:
      - wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf.template:/etc/nginx/conf.d/site.conf.template:ro
    environment:
      WP_HOST_NAME: ${WP_HOST_NAME}
    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf \
      && envsubst '${WP_HOST_NAME}' < /etc/nginx/conf.d/site.conf.template > /etc/nginx/conf.d/site.conf \
      && nginx -g 'daemon off;'"

  db:
    image: mysql:5.7.28
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - db
  #   ports:
  #     - ${PMA_PORT}:80
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  wordpress: {}
  db: {}
